const PRODUCTS = {
  LOAD: "PRODUCTS_LOAD",
  LOAD_SUCCESS: "PRODUCTS_LOAD_SUCCESS",
  LOAD_FAIL: "PRODUCTS_LOAD_FAIL"
};

const VIEW_PRODUCT = {
  SET: "VIEW_PRODUCT_SET",
  SET_SUCCESS: "VIEW_PRODUCT_SET_SUCCESS",
  SET_FAIL: "VIEW_PRODUCT_SET_FAIL"
};

const PRODUCT_DETAILS = {
  LOAD: "PRODUCT_DETAILS_LOAD",
  LOAD_SUCCESS: "PRODUCT_DETAILS_LOAD_SUCCESS",
  LOAD_FAIL: "PRODUCT_DETAILS_LOAD_FAIL"
};

const CART = {
  ADD: "CART_ADD",
  SUBTRACT: "CART_SUBTRACT"
};

export { PRODUCTS, VIEW_PRODUCT, PRODUCT_DETAILS, CART };
